### ISSUE TITLE
Update tooluseprofile-extensions.jsonld with new/revised terms and IRIs

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-contexts#99]
1. Change Metric enum paths.  Implements https://github.com/IMSGlobal/caliper-central/issues/217.
2. Change `metricValueMax` to `maxMetricValue`.  This name change aligns with other data properties that are prefixed with "max".
3.  Add `AggregateMeasureCollection`.  Aligns with ToolUse Profile.  Note: may be amended, replaced or dropped following further discussion.  But seek alignment with the profile as currently defined..

**Comment by ViktorHaag** [comment]
I like this change, but it's a vocab change that will be facing to the fixtures and sensors, so will require updates across the board, likely.

**Comment by arwhyte** [comment]
Resolved by #100
